// Bundle the plugin's browser half into the lazy-CJS factory form dsh's
// client module loader expects:
//   window.__ModuleLoader__.load({ id, factory: (require) => exports })
// Externals resolve through the loader's module table (react is a platform
// module); everything else, @opencues/runtime included, is inlined.
import * as esbuild from 'esbuild'
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const REPO = join(here, '..', '..')
// Must equal package.json's `name`: dsh's client loader keys the module
// table by package name, so a mismatch loads nothing and says nothing.
const PKG_ID = '@opencues/dsh'
const OUT = join(here, 'client.js')

/**
 * Bake the shipped defaults into the bundle.
 *
 * Without this, a user who has never installed OpenCues gets a silent
 * no-op: the config route finds no `.cues` tree, ConfigLoader reports
 * "0 cue entries, 0 blanks", the resolver builds no sources, and typing
 * `_` does nothing at all. Chrome solved the same problem by inlining
 * `defaults/` as esbuild constants; this is that, keyed to the virtual
 * paths the browser half serves.
 */
function readDefaults() {
  const root = join(REPO, 'defaults')
  // The chrome adapter band hardcodes this virtual root, and this plugin
  // runs that band — so the baked keys are `/chrome-storage/...` even
  // though there is no chrome and no chrome.storage anywhere near dsh.
  const VROOT = '/chrome-storage/.cues'
  const out = {}
  const take = (abs, virt) => {
    try { out[virt] = readFileSync(abs, 'utf8') } catch { /* absent in this checkout */ }
  }
  for (const f of ['CUES.md', 'OPENCUES.md', 'BLANKS.md', 'AUDITORS.md']) {
    take(join(root, f), `${VROOT}/${f}`)
  }
  for (const [dir, file] of [['cues', 'CUE.md'], ['blanks', 'BLANK.md'], ['auditors', 'AUDITOR.md']]) {
    let entries = []
    try { entries = readdirSync(join(root, dir), { withFileTypes: true }) } catch { continue }
    for (const e of entries) {
      if (!e.isDirectory()) continue
      take(join(root, dir, e.name, file), `${VROOT}/${dir}/${e.name}/${file}`)
    }
  }
  return out
}

const DEFAULTS = readDefaults()
console.log(`baked ${Object.keys(DEFAULTS).length} default config file(s)`)

// The NODE half needs the default OPENCUES.md as well, and cannot read the
// client bundle's baked copy. It seeds the file on a fresh user's first
// settings write — without it the write produces a two-line stub which,
// being on disk, SHADOWS the shipped default and silently turns off every
// feature the default enables explicitly (word-cues, transform-blank,
// sentence-cues, fluid-config). Emitted as a real file in the package so a
// published plugin carries it rather than depending on this repo's layout.
{
  const md = Object.entries(DEFAULTS).find(([k]) => k.endsWith('OPENCUES.md'))?.[1] ?? ''
  writeFileSync(join(here, 'default-opencues.md'), md)
  console.log(`emitted default-opencues.md (${md.length} bytes) for the node half's first-write seed`)
}

const result = await esbuild.build({
  entryPoints: [join(here, 'src/plugin.js')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  // Same treatment chrome's build uses: the runtime also serves Node hosts,
  // so its node-only paths must be kept out of the browser bundle. They are
  // lazily reached and already guarded by try/catch upstream.
  external: ['react', 'react-dom', 'node:fs', 'node:path', 'node:os', 'node:child_process', 'https'],
  write: false,
  logLevel: 'info',
  alias: {},
  define: {
    'process.env.NODE_ENV': '"production"',
    __OC_DEFAULTS__: JSON.stringify(DEFAULTS),
  },
})

const body = result.outputFiles[0].text
const wrapped = `// generated by build.mjs — do not edit
window.__ModuleLoader__.load({
  id: ${JSON.stringify(PKG_ID)},
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
${body}
    return module.exports;
  },
});
`
writeFileSync(OUT, wrapped)
console.log(`wrote ${OUT} (${(wrapped.length / 1024).toFixed(0)} kB)`)
