/**
 * Encodings, identifiers, network & colour arithmetic, and a few
 * generators. Everything runs locally. NOT here, by ruling (2026-09-19):
 * password / passphrase generators, hashes (md5, sha*), JWT decoding —
 * attack surface.
 */
import type { Calculator, CalcContext } from './types';
import { fmt, NUM, num } from './types';

const b64 = { enc: (s: string): string => typeof Buffer !== 'undefined' ? Buffer.from(s, 'utf8').toString('base64') : btoa(unescape(encodeURIComponent(s))), dec: (s: string): string => typeof Buffer !== 'undefined' ? Buffer.from(s, 'base64').toString('utf8') : decodeURIComponent(escape(atob(s))) };
const utf8 = (s: string): Uint8Array => new TextEncoder().encode(s);
const HTML: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
const UNHTML: Record<string, string> = { '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'", '&apos;': "'", '&nbsp;': ' ', '&copy;': '©', '&reg;': '®', '&mdash;': '—', '&ndash;': '–', '&hellip;': '…' };
const hexColor = (s: string): [number, number, number] | null => { const m = s.match(/#?([0-9a-f]{6}|[0-9a-f]{3})\b/i); if (!m) return null; let h = m[1]; if (h.length === 3) h = [...h].map((c) => c + c).join(''); return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)]; };
const toHex = (r: number, g: number, b: number): string => '#' + [r, g, b].map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('');
const lum = ([r, g, b]: [number, number, number]): number => { const c = [r, g, b].map((v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); }); return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]; };
const toHsl = ([r, g, b]: [number, number, number]): [number, number, number] => { r /= 255; g /= 255; b /= 255; const max = Math.max(r, g, b), min = Math.min(r, g, b); const l = (max + min) / 2; if (max === min) return [0, 0, l * 100]; const d = max - min; const s = l > 0.5 ? d / (2 - max - min) : d / (max + min); const h = max === r ? ((g - b) / d + (g < b ? 6 : 0)) : max === g ? (b - r) / d + 2 : (r - g) / d + 4; return [h * 60, s * 100, l * 100]; };
const fromHsl = (h: number, s: number, l: number): [number, number, number] => { s /= 100; l /= 100; const k = (n: number) => (n + h / 30) % 12; const a = s * Math.min(l, 1 - l); const f = (n: number) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1))); return [f(0) * 255, f(8) * 255, f(4) * 255]; };
const ip4 = (s: string): number[] | null => { const m = s.match(/\b(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})\b/); if (!m) return null; const o = m.slice(1, 5).map(Number); return o.every((x) => x <= 255) ? o : null; };
const ipStr = (n: number): string => [24, 16, 8, 0].map((sh) => (n >>> sh) & 255).join('.');
const randInt = (ctx: CalcContext, lo: number, hi: number): number => lo + Math.floor(ctx.random() * (hi - lo + 1));
const hex4 = (ctx: CalcContext): string => randInt(ctx, 0, 0xffff).toString(16).padStart(4, '0');
const NUMS = (s: string): number[] => (s.match(new RegExp(NUM, 'g')) ?? []).map(num);

export const ENCODINGS: readonly Calculator[] = [
  { id: 'base64-encode', family: 'encodings', keywords: ['base64 for', 'base64 encode', 'to base64', 'base64 of', 'base64'], arg: 'buffer', inlineArg: true, example: ['base64 for hello', 'aGVsbG8='], miss: 'nothing to encode',
    run(arg) { const t = arg.replace(/\n$/, ''); return t ? b64.enc(t) : null; } },
  { id: 'base64-decode', family: 'encodings', keywords: ['decode base64', 'base64 decode', 'from base64', 'unbase64'], arg: 'buffer', inlineArg: true, example: ['decode base64 aGVsbG8=', 'hello'], miss: 'not base64',
    run(arg) { const t = arg.trim().replace(/\s+/g, ''); if (!/^[A-Za-z0-9+/=_-]+$/.test(t) || t.length < 2) return null; try { const out = b64.dec(t.replace(/-/g, '+').replace(/_/g, '/')); return /[\x00-\x08\x0e-\x1f]/.test(out) ? `${out.length} bytes of binary` : out; } catch { return null; } } },
  { id: 'url-encode', family: 'encodings', keywords: ['url encode', 'urlencode', 'percent encode', 'uri encode', 'encode for url'], arg: 'buffer', inlineArg: true, example: ['url encode a b&c=d/e', 'a%20b%26c%3Dd%2Fe'], miss: 'nothing to encode',
    run(arg) { const t = arg.replace(/\n$/, ''); return t ? encodeURIComponent(t) : null; } },
  { id: 'url-decode', family: 'encodings', keywords: ['url decode', 'urldecode', 'percent decode', 'uri decode'], arg: 'buffer', inlineArg: true, example: ['url decode a%20b%26c', 'a b&c'], miss: 'not url-encoded',
    run(arg) { const t = arg.trim(); if (!t) return null; try { return decodeURIComponent(t.replace(/\+/g, ' ')); } catch { return null; } } },
  { id: 'html-escape', family: 'encodings', keywords: ['html escape', 'escape html', 'html encode', 'html entities for'], arg: 'buffer', inlineArg: true, example: ['html escape <a href="x">Tom & Jerry</a>', '&lt;a href=&quot;x&quot;&gt;Tom &amp; Jerry&lt;/a&gt;'], miss: 'nothing to escape',
    run(arg) { const t = arg.replace(/\n$/, ''); return t ? t.replace(/[&<>"']/g, (c) => HTML[c]) : null; } },
  { id: 'html-unescape', family: 'encodings', keywords: ['html unescape', 'unescape html', 'html decode', 'decode html'], arg: 'buffer', inlineArg: true, example: ['html unescape Tom &amp; Jerry &lt;3', 'Tom & Jerry <3'], miss: 'nothing to unescape',
    run(arg) { const t = arg.replace(/\n$/, ''); if (!t) return null; return t.replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d))).replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16))).replace(/&[a-z]+;/gi, (e) => UNHTML[e.toLowerCase()] ?? e); } },
  { id: 'hex-encode', family: 'encodings', keywords: ['hex encode', 'to hex bytes', 'hex of', 'as hex bytes', 'bytes of'], arg: 'buffer', inlineArg: true, example: ['hex encode hi', '68 69 (2 bytes)'], miss: 'nothing to encode',
    run(arg) { const t = arg.replace(/\n$/, ''); if (!t) return null; const bytes = utf8(t); return `${[...bytes].map((b) => b.toString(16).padStart(2, '0')).join(' ')} (${bytes.length} byte${bytes.length === 1 ? '' : 's'})`; } },
  { id: 'hex-decode', family: 'encodings', keywords: ['hex decode', 'from hex bytes', 'decode hex'], arg: 'buffer', inlineArg: true, example: ['hex decode 68 65 6c 6c 6f', 'hello'], miss: 'not hex bytes',
    run(arg) { const t = arg.replace(/0x|\s|:/g, ''); if (!/^[0-9a-f]+$/i.test(t) || t.length % 2) return null; const bytes = new Uint8Array(t.match(/../g)!.map((h) => parseInt(h, 16))); try { const out = new TextDecoder('utf-8', { fatal: true }).decode(bytes); return /[\x00-\x08\x0e-\x1f]/.test(out) ? `${bytes.length} bytes of binary` : out; } catch { return `${bytes.length} bytes of binary`; } } },
  { id: 'binary-of', family: 'encodings', keywords: ['binary of', 'binary for', 'in binary bytes', 'ascii binary'], arg: 'buffer', inlineArg: true, example: ['binary of hi', '01101000 01101001'], miss: 'nothing to encode',
    run(arg) { const t = arg.replace(/\n$/, ''); if (!t) return null; return [...utf8(t)].map((b) => b.toString(2).padStart(8, '0')).join(' '); } },
  { id: 'ascii-of', family: 'encodings', keywords: ['ascii of', 'ascii for', 'ascii code for', 'char code of', 'code point of', 'codepoint of', 'unicode of'], arg: 'segment', example: ['ascii of A', 'A = 65 (0x41, U+0041)'], miss: 'need one character or a code',
    run(arg) { const t = arg.trim(); const m = t.match(/^(\d{1,7})$/) ?? t.match(/^(?:u\+|0x)([0-9a-f]{1,6})$/i); if (m) { const cp = /^\d/.test(t) && !/^0x/i.test(t) ? Number(m[1]) : parseInt(m[1], 16); if (cp > 0x10ffff) return null; return `${cp} = ${JSON.stringify(String.fromCodePoint(cp)).slice(1, -1)} (0x${cp.toString(16)}, U+${cp.toString(16).toUpperCase().padStart(4, '0')})`; } const ch = [...t][0]; if (!ch || [...t].length > 1) return null; const cp = ch.codePointAt(0)!; return `${ch} = ${cp} (0x${cp.toString(16)}, U+${cp.toString(16).toUpperCase().padStart(4, '0')})`; } },
  { id: 'unix-permissions', family: 'encodings', keywords: ['chmod', 'unix permissions', 'permissions', 'file mode'], arg: 'segment', example: ['chmod 755', 'rwxr-xr-x (owner rwx · group r-x · others r-x)'], miss: 'need an octal mode (755) or rwx string',
    run(arg) { const s = arg.trim(); const oct = s.match(/\b([0-7]{3,4})\b/); const who = ['owner', 'group', 'others']; if (oct) { const d = oct[1].slice(-3).split('').map(Number); const rwx = d.map((x) => `${x & 4 ? 'r' : '-'}${x & 2 ? 'w' : '-'}${x & 1 ? 'x' : '-'}`); return `${rwx.join('')} (${rwx.map((r, i) => `${who[i]} ${r}`).join(' · ')})`; } const rwx = s.match(/\b([rwx-]{9})\b/); if (rwx) { const parts = rwx[1].match(/.{3}/g)!; const d = parts.map((p) => (p[0] === 'r' ? 4 : 0) + (p[1] === 'w' ? 2 : 0) + (p[2] === 'x' ? 1 : 0)); return `${d.join('')} (${parts.map((p, i) => `${who[i]} ${p}`).join(' · ')})`; } return null; } },
  { id: 'ip-to-int', family: 'encodings', keywords: ['ip to int', 'ip to number', 'ip as integer', 'ip to decimal'], arg: 'segment', example: ['ip to int 10.0.0.1', '167772161 (0x0a000001)'], miss: 'need an IPv4 address',
    run(arg) { const o = ip4(arg); if (!o) return null; const n = ((o[0] << 24) >>> 0) + (o[1] << 16) + (o[2] << 8) + o[3]; return `${n} (0x${n.toString(16).padStart(8, '0')})`; } },
  { id: 'int-to-ip', family: 'encodings', keywords: ['int to ip', 'number to ip', 'integer to ip'], arg: 'segment', example: ['int to ip 167772161', '10.0.0.1'], miss: 'need an integer 0–4294967295',
    run(arg) { const m = arg.match(/\d+/); if (!m) return null; const n = Number(m[0]); if (n < 0 || n > 4294967295) return null; return ipStr(n); } },
  { id: 'cidr', family: 'encodings', keywords: ['cidr', 'subnet', 'ip range for', 'netmask for'], arg: 'segment', example: ['cidr 10.0.0.0/22', '10.0.0.0 – 10.0.3.255 · 1,024 addresses (1,022 hosts) · mask 255.255.252.0'], miss: 'need a.b.c.d/n',
    run(arg) { const m = arg.match(/(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s*\/\s*(\d{1,2})/); if (!m) return null; const o = ip4(m[1]); const bits = Number(m[2]); if (!o || bits > 32) return null; const ip = ((o[0] << 24) >>> 0) + (o[1] << 16) + (o[2] << 8) + o[3]; const mask = bits === 0 ? 0 : (0xffffffff << (32 - bits)) >>> 0; const net = (ip & mask) >>> 0; const bc = (net | (~mask >>> 0)) >>> 0; const count = 2 ** (32 - bits); return `${ipStr(net)} – ${ipStr(bc)} · ${fmt(count).replace(/\B(?=(\d{3})+(?!\d))/g, ',')} addresses (${count > 2 ? fmt(count - 2).replace(/\B(?=(\d{3})+(?!\d))/g, ',') : count} hosts) · mask ${ipStr(mask)}`; } },
  { id: 'is-valid', family: 'encodings', keywords: ['is valid', 'validate', 'is this a valid', 'check format'], arg: 'segment', example: ['is valid email a.b@example.com', 'a.b@example.com: valid email format'], miss: 'need email / ipv4 / ipv6 / uuid / url / iban / isbn and a value',
    run(arg) { const s = arg.trim(); const kind = (s.match(/\b(email|ipv4|ipv6|ip|uuid|url|iban|isbn|hex colou?r|mac)\b/i) ?? [])[1]?.toLowerCase(); let v = kind ? s.replace(new RegExp(`\\b${kind}\\b`, 'i'), ' ').replace(/\s+/g, ' ').trim() : ''; for (let i = 0; i < 4; i++) v = v.replace(/^(?:is|this|a|an|for|valid|address|format|colou?r)\s+/i, '').replace(/\s+(?:address|format|valid)$/i, ''); if (!kind || !v) return null; const ok = (() => { switch (kind) { case 'email': return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v); case 'ipv4': case 'ip': return ip4(v) !== null && /^\d{1,3}(\.\d{1,3}){3}$/.test(v); case 'ipv6': return /^[0-9a-f:]+$/i.test(v) && v.includes(':') && (v.match(/:/g) ?? []).length <= 7; case 'uuid': return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v); case 'url': try { new URL(v); return /^https?:\/\//.test(v); } catch { return false; } case 'iban': { const t = v.replace(/\s/g, '').toUpperCase(); if (!/^[A-Z]{2}\d{2}[A-Z0-9]{11,30}$/.test(t)) return false; const r = (t.slice(4) + t.slice(0, 4)).replace(/[A-Z]/g, (c) => String(c.charCodeAt(0) - 55)); let mod = 0; for (const d of r) mod = (mod * 10 + Number(d)) % 97; return mod === 1; } case 'isbn': { const t = v.replace(/[-\s]/g, ''); if (/^\d{9}[\dX]$/i.test(t)) { let sum = 0; for (let i = 0; i < 10; i++) sum += (t[i].toUpperCase() === 'X' ? 10 : Number(t[i])) * (10 - i); return sum % 11 === 0; } if (/^\d{13}$/.test(t)) { let sum = 0; for (let i = 0; i < 13; i++) sum += Number(t[i]) * (i % 2 ? 3 : 1); return sum % 10 === 0; } return false; } case 'mac': return /^([0-9a-f]{2}[:-]){5}[0-9a-f]{2}$/i.test(v); default: return /^#?([0-9a-f]{3}|[0-9a-f]{6})$/i.test(v); } })(); return `${v}: ${ok ? 'valid' : 'NOT a valid'} ${kind} ${kind === 'iban' || kind === 'isbn' ? 'checksum' : 'format'}`; } },
  { id: 'color-contrast', family: 'encodings', keywords: ['color contrast', 'colour contrast', 'contrast ratio', 'contrast between', 'wcag contrast'], arg: 'segment', example: ['color contrast #fff #777', '4.48:1 — AA normal text ✗, AA large ✓, AAA ✗'], miss: 'need two hex colours',
    run(arg) { const cs = [...arg.matchAll(/#?([0-9a-f]{6}|[0-9a-f]{3})\b/gi)].map((m) => hexColor(m[0])!); if (cs.length < 2) return null; const [a, b] = [lum(cs[0]), lum(cs[1])]; const ratio = (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05); const r = Math.round(ratio * 100) / 100; return `${r}:1 — AA normal text ${ratio >= 4.5 ? '✓' : '✗'}, AA large ${ratio >= 3 ? '✓' : '✗'}, AAA ${ratio >= 7 ? '✓' : '✗'}`; } },
  { id: 'hex-to-hsl', family: 'encodings', keywords: ['hex to hsl', 'hsl for', 'hsl of', 'to hsl', 'in hsl'], arg: 'segment', example: ['hex to hsl #ff6347', 'hsl(9, 100%, 64%) · rgb(255, 99, 71)'], miss: 'need a hex colour',
    run(arg) { const c = hexColor(arg); if (!c) return null; const [h, s, l] = toHsl(c); return `hsl(${Math.round(h)}, ${Math.round(s)}%, ${Math.round(l)}%) · rgb(${c.join(', ')})`; } },
  { id: 'lighten', family: 'encodings', keywords: ['lighten', 'darken', 'lighter', 'darker'], arg: 'segment', keywordIsArg: true, example: ['lighten #ff6347 by 20%', '#ffb9ad (hsl 9, 100%, 84%)'], miss: 'need lighten|darken <hex> by <n>%',
    run(arg) { const c = hexColor(arg); const p = NUMS(arg.replace(/#[0-9a-f]+/i, ''))[0] ?? 10; if (!c) return null; const [h, s, l] = toHsl(c); const nl = /darker|darken/i.test(arg) ? Math.max(0, l - p) : Math.min(100, l + p); const [r, g, b] = fromHsl(h, s, nl); return `${toHex(r, g, b)} (hsl ${Math.round(h)}, ${Math.round(s)}%, ${Math.round(nl)}%)`; } },
  { id: 'json-pretty', family: 'encodings', keywords: ['json pretty', 'pretty json', 'format json', 'prettify json'], arg: 'buffer', inlineArg: true, transform: true, example: ['json pretty {"a":1,"b":[1,2]}', '{\n  "a": 1,\n  "b": [\n    1,\n    2\n  ]\n}'], miss: 'not valid JSON',
    run(arg) { try { return JSON.stringify(JSON.parse(arg), null, 2); } catch { return null; } } },
  { id: 'json-minify', family: 'encodings', keywords: ['json minify', 'minify json', 'compact json', 'json compact'], arg: 'buffer', inlineArg: true, transform: true, example: ['json minify { "a": 1 }', '{"a":1}'], miss: 'not valid JSON',
    run(arg) { try { return JSON.stringify(JSON.parse(arg)); } catch { return null; } } },
  { id: 'json-validate', family: 'encodings', keywords: ['json validate', 'validate json', 'is valid json', 'check json'], arg: 'buffer', inlineArg: true, example: ['json validate {"a":1}', 'valid JSON · object with 1 key'], miss: 'nothing to validate',
    run(arg) { if (!arg.trim()) return null; try { const v = JSON.parse(arg); const kind = Array.isArray(v) ? `array of ${v.length}` : v && typeof v === 'object' ? `object with ${Object.keys(v).length} key${Object.keys(v).length === 1 ? '' : 's'}` : typeof v; return `valid JSON · ${kind}`; } catch (e) { return `invalid JSON: ${(e as Error).message.replace(/^JSON\.parse: /, '').slice(0, 80)}`; } } },
  // ── generators: never cached, never replayed by undo ──
  { id: 'uuid', family: 'encodings', keywords: ['uuid', 'new uuid', 'generate uuid', 'guid', 'uuid v4', 'uuid v7'], arg: 'segment', optionalArg: true, generator: true, keywordIsArg: true, example: ['uuid', 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'], miss: '',
    run(arg, ctx) { if (/v7/.test(arg)) { const t = ctx.now().getTime(); const th = t.toString(16).padStart(12, '0'); return `${th.slice(0, 8)}-${th.slice(8, 12)}-7${hex4(ctx).slice(1)}-${((randInt(ctx, 0, 0x3fff) | 0x8000)).toString(16)}-${hex4(ctx)}${hex4(ctx)}${hex4(ctx)}`; } const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto; if (c?.randomUUID) return c.randomUUID(); return `${hex4(ctx)}${hex4(ctx)}-${hex4(ctx)}-4${hex4(ctx).slice(1)}-${((randInt(ctx, 0, 0x3fff) | 0x8000)).toString(16)}-${hex4(ctx)}${hex4(ctx)}${hex4(ctx)}`; } },
  { id: 'random', family: 'encodings', keywords: ['random number', 'random between', 'random from', 'random'], arg: 'segment', optionalArg: true, generator: true, example: ['random 1 to 100', '50'], miss: '',
    run(arg, ctx) { const xs = NUMS(arg); const [lo, hi] = xs.length >= 2 ? [Math.min(xs[0], xs[1]), Math.max(xs[0], xs[1])] : xs.length === 1 ? [1, xs[0]] : [1, 100]; if (!Number.isInteger(lo) || !Number.isInteger(hi)) return fmt(lo + ctx.random() * (hi - lo)); return String(randInt(ctx, lo, hi)); } },
  { id: 'random-pick', family: 'encodings', keywords: ['random pick', 'pick one of', 'pick from', 'choose one of', 'pick one'], arg: 'segment', generator: true, example: ['random pick red, green, blue', 'green'], miss: 'need a list (a, b, c)',
    run(arg, ctx) { const items = arg.split(/\s*,\s*|\s+or\s+|\s+\/\s+/).map((s) => s.trim()).filter(Boolean); if (items.length < 2) return null; return items[randInt(ctx, 0, items.length - 1)]; } },
  { id: 'coin-flip', family: 'encodings', keywords: ['coin flip', 'flip a coin', 'heads or tails', 'toss a coin'], arg: 'none', generator: true, example: ['coin flip', 'heads'], miss: '',
    run(_arg, ctx) { return ctx.random() < 0.5 ? 'heads' : 'tails'; } },
  { id: 'dice', family: 'encodings', keywords: ['roll', 'dice', 'roll dice', 'roll a d'], arg: 'segment', optionalArg: true, generator: true, keywordIsArg: true, example: ['roll 2d6', '7 (4 + 3)'], miss: 'need NdM (2d6) or a die size',
    run(arg, ctx) { const m = arg.toLowerCase().match(/(\d*)\s*d\s*(\d+)(?:\s*([+-])\s*(\d+))?/); const n = m ? Math.min(100, Number(m[1] || 1)) : 1, sides = m ? Number(m[2]) : 6; if (sides < 2 || sides > 1000) return null; const rolls = Array.from({ length: n }, () => randInt(ctx, 1, sides)); const mod = m?.[3] ? (m[3] === '+' ? 1 : -1) * Number(m[4]) : 0; const total = rolls.reduce((a, b) => a + b, 0) + mod; return n === 1 && !mod ? String(total) : `${total} (${rolls.join(' + ')}${mod ? ` ${mod > 0 ? '+' : '-'} ${Math.abs(mod)}` : ''})`; } },
];
