/**
 * Percent & money — every one closed-form. The VAT rate is the
 * `vat-rate` scalar (default 20), never a guess; nothing here touches an
 * exchange rate or an inflation series (live data stays on the network
 * blanks).
 */
import type { Calculator, CalcContext } from './types';
import { fmt, withCommas, NUM, num } from './types';

const money = (n: number): string => { const r = Math.round(n * 100) / 100; const s = withCommas(r); return Number.isInteger(r) ? s : /\.\d$/.test(s) ? `${s}0` : s; };
const pct = (n: number): string => `${fmt(Math.round(n * 100) / 100)}%`;
const nums = (s: string): number[] => (s.replace(/(\d),(\d{3})\b/g, '$1$2').match(new RegExp(NUM, 'g')) ?? []).map(num).filter(Number.isFinite);
const WORD_NUM: Record<string, number> = { one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10, eleven: 11, twelve: 12 };
const vatRate = (ctx: CalcContext): number => { const v = Number((ctx.setting('vat-rate') ?? '20').replace('%', '')); return Number.isFinite(v) && v >= 0 ? v : 20; };
/** `X% of|on Y` / `Y with X%` → [rate, amount]; the rate is whichever number carries the % */
const rateAnd = (s: string): [number, number] | null => { const r = s.match(new RegExp(String.raw`(${NUM})\s*(?:%|percent|pct)`)); if (!r) return null; const rest = s.replace(r[0], ' '); const a = nums(rest)[0]; return a === undefined ? null : [num(r[1]), a]; };
const years = (s: string): number | null => { const m = s.match(new RegExp(String.raw`(${NUM})\s*(?:years?|yrs?|y)\b`)); if (m) return num(m[1]); const mo = s.match(new RegExp(String.raw`(${NUM})\s*(?:months?|mo)\b`)); return mo ? num(mo[1]) / 12 : null; };
const pmt = (principal: number, annualRate: number, months: number): number => { const r = annualRate / 100 / 12; return r === 0 ? principal / months : principal * r / (1 - Math.pow(1 + r, -months)); };

export const MONEY: readonly Calculator[] = [
  { id: 'percent-off', family: 'money', keywords: ['% off', 'percent off', 'off'], arg: 'segment', keywordIsArg: true, phrase: new RegExp(String.raw`^(${NUM})\s*(?:%|percent)\s+off\s+(${NUM})$`, 'i'), example: ['20% off 85', '68 (saves 17)'], miss: 'need <rate>% off <price>',
    run(arg) { const m = arg.toLowerCase().match(new RegExp(String.raw`(${NUM})\s*(?:%|percent)\s+off\s+(?:of\s+)?(${NUM})`)) ?? arg.toLowerCase().match(new RegExp(String.raw`(${NUM})\s+(?:at|with)\s+(${NUM})\s*(?:%|percent)\s+off`)); if (!m) return null; const [r, p] = /off\s+(?:of\s+)?[\d,.-]+$/.test(m[0]) ? [num(m[1]), num(m[2])] : [num(m[2]), num(m[1])]; return `${money(p * (1 - r / 100))} (saves ${money(p * r / 100)})`; } },
  { id: 'percent-of-what', family: 'money', keywords: ['is what percent of', 'is what % of', 'as a percentage of', 'what percent of'], arg: 'segment', keywordIsArg: true, phrase: new RegExp(String.raw`^(${NUM})\s+(?:is what (?:percent|%) of|as a percentage of|out of)\s+(${NUM})$`, 'i'), example: ['85 is what percent of 340', '25%'], miss: 'need <part> is what percent of <whole>',
    run(arg) { const s = arg.toLowerCase(); let m = s.match(new RegExp(String.raw`(${NUM})\s+(?:is (?:what )?(?:percent|%) of|as a percentage of|out of)\s+(${NUM})`)); if (!m) { m = s.match(new RegExp(String.raw`what (?:percent|%) of\s+(${NUM})\s+is\s+(${NUM})`)); if (m) m = [m[0], m[2], m[1]]; } if (!m) return null; const whole = num(m[2]); if (whole === 0) return null; return pct(num(m[1]) / whole * 100); } },
  { id: 'percent-change', family: 'money', keywords: ['percent change', 'percentage change', 'percent increase', 'percent decrease', 'percentage increase', 'percentage decrease', 'change from'], arg: 'segment', example: ['percent change 80 to 92', '+15% (80 → 92, +12)'], miss: 'need <from> to <to>',
    run(arg) { const [a, b] = nums(arg); if (a === undefined || b === undefined || a === 0) return null; const d = (b - a) / Math.abs(a) * 100; return `${d >= 0 ? '+' : ''}${pct(d)} (${fmt(a)} → ${fmt(b)}, ${d >= 0 ? '+' : ''}${fmt(b - a)})`; } },
  { id: 'percent-plus', family: 'money', keywords: ['plus %', 'minus %'], arg: 'segment', keywordIsArg: true, phrase: new RegExp(String.raw`^(${NUM})\s*(?:plus|\+|minus|-|less)\s*(${NUM})\s*(?:%|percent)$`, 'i'), example: ['85 plus 20%', '102 (+17)'], miss: 'need <amount> plus|minus <rate>%',
    run(arg) { const m = arg.toLowerCase().match(new RegExp(String.raw`(${NUM})\s*(plus|\+|minus|-|less)\s*(${NUM})\s*(?:%|percent)`)); if (!m) return null; const a = num(m[1]), r = num(m[3]); const sign = m[2] === 'plus' || m[2] === '+' ? 1 : -1; const d = a * r / 100 * sign; return `${money(a + d)} (${d >= 0 ? '+' : ''}${money(d)})`; } },
  { id: 'tip', family: 'money', keywords: ['tip'], arg: 'segment', example: ['tip 15% on 64.20', 'tip 9.63 · total 73.83'], miss: 'need tip <rate>% on <bill>',
    run(arg) { const s = arg.toLowerCase(); const ra = rateAnd(s); const rate = ra ? ra[0] : 15; const bill = ra ? ra[1] : nums(s)[0]; if (bill === undefined) return null; const ways = s.match(/(?:split|between|for)\s+(\d+|[a-z]+)\s*(?:ways?|people|of us)?/); const n = ways ? (WORD_NUM[ways[1]] ?? Number(ways[1])) : 1; const tip = bill * rate / 100, total = bill + tip; return `tip ${money(tip)}${ra ? '' : ' (15%)'} · total ${money(total)}${n > 1 ? ` · ${money(total / n)} each (${n} ways)` : ''}`; } },
  { id: 'split', family: 'money', keywords: ['split'], arg: 'segment', example: ['split 143 four ways', '35.75 each (4 ways)'], miss: 'need split <amount> <n> ways',
    run(arg) { const s = arg.toLowerCase(); const m = s.match(/(\d+|[a-z]+)\s*(?:ways?|people|of us|persons|between)/) ?? s.match(/between\s+(\d+|[a-z]+)/); if (!m) return null; const n = WORD_NUM[m[1]] ?? Number(m[1]); if (!Number.isFinite(n) || n < 1) return null; const amount = nums(s.replace(m[0], ' ').replace(new RegExp(String.raw`(${NUM})\s*(?:%|percent)\s*tip`), ' '))[0]; if (amount === undefined) return null; const t = s.match(new RegExp(String.raw`(${NUM})\s*(?:%|percent)\s*tip`)); const tip = t ? amount * num(t[1]) / 100 : 0; return `${money((amount + tip) / n)} each (${n} ways${tip ? `, total ${money(amount + tip)} with ${fmt(num(t![1]))}% tip` : ''})`; } },
  { id: 'vat', family: 'money', keywords: ['plus vat', 'inc vat', 'including vat', 'with vat', 'ex vat', 'excluding vat', 'without vat', 'minus vat', 'before vat', 'vat on', 'vat'], arg: 'segment', keywordIsArg: true, example: ['120 plus vat', '144 (20% VAT: 24)'], miss: 'need <amount> plus vat / ex vat / vat on <amount>',
    run(arg, ctx) { const s = arg.toLowerCase(); const rate = (s.match(new RegExp(String.raw`(${NUM})\s*%`)) ? num(s.match(new RegExp(String.raw`(${NUM})\s*%`))![1]) : vatRate(ctx)); const a = nums(s.replace(new RegExp(String.raw`(${NUM})\s*%`), ' '))[0]; if (a === undefined) return null; if (/\b(ex|excluding|without|minus|before)\b/.test(s)) { const net = a / (1 + rate / 100); return `${money(net)} (${fmt(rate)}% VAT: ${money(a - net)})`; } if (/^vat on\b|\bvat on\b/.test(s)) return `${money(a * rate / 100)} (${fmt(rate)}% of ${money(a)} → ${money(a * (1 + rate / 100))} inc)`; return `${money(a * (1 + rate / 100))} (${fmt(rate)}% VAT: ${money(a * rate / 100)})`; } },
  { id: 'compound', family: 'money', keywords: ['compound', 'compound interest', 'grow', 'invest'], arg: 'segment', example: ['compound 1000 at 5% for 10 years', '1,628.89 (interest 628.89, yearly)'], miss: 'need <principal> at <rate>% for <n> years',
    run(arg) { const s = arg.toLowerCase(); const ra = rateAnd(s); const y = years(s); if (!ra || y === null) return null; const [r, p] = ra; const monthly = /monthly/.test(s), daily = /daily/.test(s); const n = daily ? 365 : monthly ? 12 : 1; const total = p * Math.pow(1 + r / 100 / n, n * y); return `${money(total)} (interest ${money(total - p)}, ${daily ? 'daily' : monthly ? 'monthly' : 'yearly'})`; } },
  { id: 'simple-interest', family: 'money', keywords: ['simple interest'], arg: 'segment', example: ['simple interest 1000 at 5% for 3 years', '150 (total 1,150)'], miss: 'need <principal> at <rate>% for <n> years',
    run(arg) { const s = arg.toLowerCase(); const ra = rateAnd(s); const y = years(s); if (!ra || y === null) return null; const [r, p] = ra; const i = p * r / 100 * y; return `${money(i)} (total ${money(p + i)})`; } },
  { id: 'monthly-payment', family: 'money', keywords: ['monthly payment', 'mortgage', 'loan payment', 'repayment on', 'repayments on'], arg: 'segment', example: ['monthly payment on 250000 at 6% over 30 years', '1,498.88/month (total 539,595.47, interest 289,595.47)'], miss: 'need <amount> at <rate>% over <n> years',
    run(arg) { const s = arg.toLowerCase(); const ra = rateAnd(s); const y = years(s); if (!ra || y === null) return null; const [r, p] = ra; const months = Math.round(y * 12); const m = pmt(p, r, months); return `${money(m)}/month (total ${money(m * months)}, interest ${money(m * months - p)})`; } },
  { id: 'apr-to-monthly', family: 'money', keywords: ['apr to monthly', 'monthly rate for', 'apr'], arg: 'segment', example: ['apr to monthly 12%', '1% per month (12.68% effective annual)'], miss: 'need an APR %',
    run(arg) { const r = nums(arg)[0]; if (r === undefined) return null; return `${pct(r / 12)} per month (${pct((Math.pow(1 + r / 1200, 12) - 1) * 100)} effective annual)`; } },
  { id: 'doubling-time', family: 'money', keywords: ['doubling time', 'time to double', 'years to double'], arg: 'segment', example: ['doubling time at 7%', '10.24 years (rule of 72: 10.3)'], miss: 'need a rate %',
    run(arg) { const r = nums(arg)[0]; if (!r) return null; return `${fmt(Math.round(Math.log(2) / Math.log(1 + r / 100) * 100) / 100)} years (rule of 72: ${fmt(Math.round(72 / r * 10) / 10)})`; } },
  { id: 'margin', family: 'money', keywords: ['margin', 'markup', 'profit on'], arg: 'segment', example: ['margin cost 40 sell 60', 'margin 33.33% · markup 50% · profit 20'], miss: 'need cost <c> sell <s>',
    run(arg) { const s = arg.toLowerCase(); const c = s.match(new RegExp(String.raw`(?:cost|bought|buy)\s*(?:of|at|for)?\s*(${NUM})`)); const p = s.match(new RegExp(String.raw`(?:sell|sold|price|sells?)\s*(?:of|at|for)?\s*(${NUM})`)); let cost: number, sell: number; if (c && p) { cost = num(c[1]); sell = num(p[1]); } else { const xs = nums(s); if (xs.length < 2) return null; [cost, sell] = xs; } if (!cost || !sell) return null; return `margin ${pct((sell - cost) / sell * 100)} · markup ${pct((sell - cost) / cost * 100)} · profit ${money(sell - cost)}`; } },
  { id: 'break-even', family: 'money', keywords: ['break even', 'breakeven'], arg: 'segment', example: ['break even fixed 5000 price 25 cost 10', '334 units (333.3 → revenue 8,350)'], miss: 'need fixed <f> price <p> cost <c>',
    run(arg) { const s = arg.toLowerCase(); const f = s.match(new RegExp(String.raw`fixed\s*(?:costs?)?\s*(?:of)?\s*(${NUM})`)), p = s.match(new RegExp(String.raw`price\s*(?:of)?\s*(${NUM})`)), c = s.match(new RegExp(String.raw`(?:variable\s*)?cost\s*(?:of)?\s*(${NUM})`)); if (!f || !p || !c) return null; const margin = num(p[1]) - num(c[1]); if (margin <= 0) return null; const units = num(f[1]) / margin; return `${Math.ceil(units)} units (${fmt(Math.round(units * 10) / 10)} → revenue ${money(Math.ceil(units) * num(p[1]))})`; } },
  { id: 'per-hour', family: 'money', keywords: ['per hour', 'hourly', 'an hour'], arg: 'segment', keywordIsArg: true, phrase: new RegExp(String.raw`^(${NUM})\s*(?:k)?\s*(?:a|per|\/)\s*year\s+(?:per hour|hourly|an hour)$`, 'i'), example: ['80000 a year per hour', '38.46/h (40 h/wk, 52 wk)'], miss: 'need <salary> a year per hour',
    run(arg) { const s = arg.toLowerCase(); const m = s.match(new RegExp(String.raw`(${NUM})\s*(k)?\s*(?:a|per|\/)?\s*(?:year|yr|annum|annually|pa)`)); if (!m) return null; const salary = num(m[1]) * (m[2] ? 1000 : 1); const hrs = num((s.match(new RegExp(String.raw`(${NUM})\s*(?:h|hours?)\s*(?:\/|a|per)\s*(?:wk|week)`)) ?? [])[1] ?? '40'); return `${money(salary / (hrs * 52))}/h (${hrs} h/wk, 52 wk)`; } },
  { id: 'per-year', family: 'money', keywords: ['per year', 'annually', 'a year', 'annual salary'], arg: 'segment', keywordIsArg: true, phrase: new RegExp(String.raw`^(${NUM})\s*(?:an|per|\/)\s*(?:hour|h|hr)\s+(?:per year|annually|a year)$`, 'i'), example: ['35 an hour per year', '72,800/yr (40 h/wk, 52 wk) · 6,066.67/month'], miss: 'need <rate> an hour per year',
    run(arg) { const s = arg.toLowerCase(); const m = s.match(new RegExp(String.raw`(${NUM})\s*(?:an|per|\/)?\s*(?:hour|h|hr)\b`)); if (!m) return null; const hrs = num((s.match(new RegExp(String.raw`(${NUM})\s*(?:h|hours?)\s*(?:\/|a|per)\s*(?:wk|week)`)) ?? [])[1] ?? '40'); const yr = num(m[1]) * hrs * 52; return `${money(yr)}/yr (${hrs} h/wk, 52 wk) · ${money(yr / 12)}/month`; } },
  { id: 'unit-price', family: 'money', keywords: ['unit price', 'price each', 'each'], arg: 'segment', keywordIsArg: true, phrase: new RegExp(String.raw`^(${NUM})\s+for\s+(${NUM})\s+each$`, 'i'), example: ['unit price 6 for 4.20', '0.70 each'], miss: 'need <n> for <price>',
    run(arg) { const m = arg.toLowerCase().match(new RegExp(String.raw`(${NUM})\s+for\s+(${NUM})`)); if (!m) return null; const n = num(m[1]), p = num(m[2]); if (!n) return null; return `${money(p / n)} each`; } },
  { id: 'discount-to-reach', family: 'money', keywords: ['discount to reach', 'discount from', 'what discount'], arg: 'segment', example: ['discount to reach 85 from 100', '15% off'], miss: 'need <target> from <price>',
    run(arg) { const s = arg.toLowerCase(); const m = s.match(new RegExp(String.raw`(${NUM})\s+from\s+(${NUM})`)) ?? s.match(new RegExp(String.raw`from\s+(${NUM})\s+to\s+(${NUM})`)); if (!m) return null; const [t, p] = /^from/.test(m[0]) ? [num(m[2]), num(m[1])] : [num(m[1]), num(m[2])]; if (!p) return null; return `${pct((1 - t / p) * 100)} off`; } },
  { id: 'cagr', family: 'money', keywords: ['cagr', 'growth rate', 'annual growth'], arg: 'segment', example: ['cagr 100 to 250 over 5 years', '20.11%/yr'], miss: 'need <start> to <end> over <n> years',
    run(arg) { const s = arg.toLowerCase(); const y = years(s); const [a, b] = nums(s.replace(new RegExp(String.raw`(${NUM})\s*(?:years?|yrs?|y|months?|mo)\b`), ' ')); if (a === undefined || b === undefined || y === null || a <= 0 || y <= 0) return null; return `${pct((Math.pow(b / a, 1 / y) - 1) * 100)}/yr`; } },
];
