/**
 * Geometry, physics, fitness, media & network arithmetic — formulas and a
 * few constants. Units in, units out; SI unless the writer wrote otherwise.
 */
import type { Calculator } from './types';
import { fmt, withCommas, NUM, num } from './types';

const nums = (s: string): number[] => (s.match(new RegExp(NUM, 'g')) ?? []).map(num).filter(Number.isFinite);
const r2 = (n: number): number => Math.round(n * 100) / 100;
const named = (s: string, key: string): number | null => { const m = s.match(new RegExp(String.raw`\b${key}\s*(?:of|=|:|is)?\s*(${NUM})`)); return m ? num(m[1]) : null; };
const toM = (v: number, u: string): number => ({ m: 1, meter: 1, metre: 1, meters: 1, metres: 1, cm: 0.01, mm: 0.001, km: 1000, ft: 0.3048, foot: 0.3048, feet: 0.3048, in: 0.0254, inch: 0.0254, inches: 0.0254, mi: 1609.344, mile: 1609.344, miles: 1609.344, yd: 0.9144, yard: 0.9144, yards: 0.9144 } as Record<string, number>)[u] * v;
const toKg = (v: number, u: string): number => ({ kg: 1, kilo: 1, kilos: 1, kilogram: 1, kilograms: 1, g: 0.001, lb: 0.4536, lbs: 0.4536, pound: 0.4536, pounds: 0.4536, st: 6.35, stone: 6.35 } as Record<string, number>)[u] * v;
const LEN = 'm|meters?|metres?|cm|mm|km|ft|foot|feet|in|inch|inches|mi|miles?|yd|yards?';
const MASS = 'kg|kilos?|kilograms?|g|lbs?|pounds?|st|stone';
const clock = (secs: number): string => { const h = Math.floor(secs / 3600), m = Math.floor((secs % 3600) / 60), s = Math.round(secs % 60); return h ? `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}` : `${m}:${String(s).padStart(2, '0')}`; };
const parseClockSecs = (s: string): number | null => { const m = s.match(/(\d+):(\d{2})(?::(\d{2}))?/); if (!m) return null; return m[3] ? Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3]) : Number(m[1]) * 60 + Number(m[2]); };
const distKm = (s: string): number | null => { const m = s.match(new RegExp(String.raw`(${NUM})\s*(k|km|kilometers?|kilometres?|mi|miles?|m|meters?|metres?)\b`)); if (!m) return null; const v = num(m[1]); const u = m[2]; return /^k/.test(u) ? v : /^mi/.test(u) ? v * 1.609344 : v / 1000; };

const PLANETS: Record<string, { g: number; esc: number; day: string; year: string }> = {
  mercury: { g: 3.7, esc: 4.25, day: '58.6 Earth days', year: '88 days' }, venus: { g: 8.87, esc: 10.36, day: '243 Earth days', year: '225 days' }, earth: { g: 9.81, esc: 11.19, day: '23 h 56 min', year: '365.25 days' },
  moon: { g: 1.62, esc: 2.38, day: '29.5 Earth days', year: '27.3 days (around Earth)' }, mars: { g: 3.72, esc: 5.03, day: '24 h 37 min', year: '687 days' }, jupiter: { g: 24.79, esc: 59.5, day: '9 h 56 min', year: '11.9 years' },
  saturn: { g: 10.44, esc: 35.5, day: '10 h 42 min', year: '29.5 years' }, uranus: { g: 8.87, esc: 21.3, day: '17 h 14 min', year: '84 years' }, neptune: { g: 11.15, esc: 23.5, day: '16 h 6 min', year: '165 years' }, pluto: { g: 0.62, esc: 1.21, day: '6.4 Earth days', year: '248 years' }, sun: { g: 274, esc: 617.5, day: '25 Earth days (equator)', year: '—' },
};
const CONSTANTS: Record<string, string> = {
  'speed of light': '299,792,458 m/s (c; ≈ 3.0 × 10⁸ m/s, 1 079 252 849 km/h)', 'speed of sound': '343 m/s in air at 20 °C (1,235 km/h, 767 mph); 1,480 m/s in water', 'gravity': '9.81 m/s² on Earth (g)', 'gravitational constant': 'G = 6.674 × 10⁻¹¹ N·m²/kg²',
  'planck constant': 'h = 6.626 × 10⁻³⁴ J·s', 'avogadro': '6.022 × 10²³ per mol', 'avogadro constant': '6.022 × 10²³ per mol', 'boltzmann constant': 'k = 1.381 × 10⁻²³ J/K', 'electron charge': 'e = 1.602 × 10⁻¹⁹ C', 'absolute zero': '−273.15 °C (0 K, −459.67 °F)',
  'golden ratio': 'φ = 1.6180339887', 'euler': 'e = 2.7182818285', 'pi': 'π = 3.1415926536', 'astronomical unit': '149,597,870.7 km (Earth–Sun)', 'light year': '9.461 × 10¹² km', 'parsec': '3.086 × 10¹³ km (3.26 light years)',
  'distance to the moon': '384,400 km on average (1.28 light-seconds)', 'distance to the sun': '149.6 million km (8 min 20 s at light speed)', 'radius of the earth': '6,371 km on average', 'circumference of the earth': '40,075 km at the equator',
};
const NOTES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

export const PHYSICS: readonly Calculator[] = [
  { id: 'area-of', family: 'physics', keywords: ['area of'], arg: 'segment', example: ['area of a circle radius 4', '50.27 (π × 4²)'], miss: 'need a circle radius r / square side s / rectangle a by b / triangle base b height h',
    run(arg) { const s = arg.toLowerCase(); const r = named(s, 'radius') ?? named(s, 'r'); const d = named(s, 'diameter'); if (/circle/.test(s) && (r !== null || d !== null)) { const rr = r ?? d! / 2; return `${fmt(r2(Math.PI * rr * rr))} (π × ${fmt(rr)}²)`; } if (/square/.test(s)) { const a = named(s, 'side') ?? nums(s)[0]; return a === undefined ? null : `${fmt(r2(a * a))} (${fmt(a)}²)`; } if (/rectangle|rect\b/.test(s)) { const [a, b] = nums(s); return b === undefined ? null : `${fmt(r2(a * b))} (${fmt(a)} × ${fmt(b)})`; } if (/triangle/.test(s)) { const b = named(s, 'base') ?? nums(s)[0], h = named(s, 'height') ?? nums(s)[1]; return b === undefined || h === undefined ? null : `${fmt(r2(b * h / 2))} (½ × ${fmt(b)} × ${fmt(h)})`; } if (/trapez/.test(s)) { const [a, b, h] = nums(s); return h === undefined ? null : `${fmt(r2((a + b) / 2 * h))}`; } if (/ellipse/.test(s)) { const [a, b] = nums(s); return b === undefined ? null : `${fmt(r2(Math.PI * a * b))} (π × ${a} × ${b})`; } return null; } },
  { id: 'circumference', family: 'physics', keywords: ['circumference of', 'circumference', 'perimeter of'], arg: 'segment', example: ['circumference of a circle radius 4', '25.13 (2π × 4)'], miss: 'need a radius or diameter (or a square / rectangle)',
    run(arg) { const s = arg.toLowerCase(); if (/square/.test(s)) { const a = nums(s)[0]; return a === undefined ? null : `${fmt(4 * a)}`; } if (/rectangle/.test(s)) { const [a, b] = nums(s); return b === undefined ? null : `${fmt(2 * (a + b))}`; } const r = named(s, 'radius') ?? named(s, 'r'); const d = named(s, 'diameter') ?? (r === null ? nums(s)[0] : null); const rr = r ?? (d !== null && d !== undefined ? d / 2 : null); if (rr === null) return null; return `${fmt(r2(2 * Math.PI * rr))} (2π × ${fmt(rr)})`; } },
  { id: 'volume-of', family: 'physics', keywords: ['volume of'], arg: 'segment', example: ['volume of a sphere radius 2', '33.51 (4⁄3 π × 2³)'], miss: 'need a sphere radius r / cube side s / cylinder radius r height h / cone / box a by b by c',
    run(arg) { const s = arg.toLowerCase(); const r = named(s, 'radius') ?? named(s, 'r') ?? (named(s, 'diameter') !== null ? named(s, 'diameter')! / 2 : null); const h = named(s, 'height') ?? named(s, 'h'); if (/sphere|ball/.test(s) && r !== null) return `${fmt(r2(4 / 3 * Math.PI * r ** 3))} (4⁄3 π × ${fmt(r)}³)`; if (/cube/.test(s)) { const a = named(s, 'side') ?? nums(s)[0]; return a === undefined ? null : `${fmt(r2(a ** 3))} (${fmt(a)}³)`; } if (/cylinder|can|tank/.test(s) && r !== null && h !== null) return `${fmt(r2(Math.PI * r * r * h))} (π × ${fmt(r)}² × ${fmt(h)})`; if (/cone/.test(s) && r !== null && h !== null) return `${fmt(r2(Math.PI * r * r * h / 3))} (⅓ π × ${fmt(r)}² × ${fmt(h)})`; if (/box|cuboid|room/.test(s)) { const [a, b, c] = nums(s); return c === undefined ? null : `${fmt(r2(a * b * c))} (${a} × ${b} × ${c})`; } return null; } },
  { id: 'surface-area', family: 'physics', keywords: ['surface area of'], arg: 'segment', example: ['surface area of a sphere radius 2', '50.27 (4π × 2²)'], miss: 'need a sphere radius r / cube side s / cylinder radius r height h',
    run(arg) { const s = arg.toLowerCase(); const r = named(s, 'radius') ?? named(s, 'r'); const h = named(s, 'height') ?? named(s, 'h'); if (/sphere/.test(s) && r !== null) return `${fmt(r2(4 * Math.PI * r * r))} (4π × ${fmt(r)}²)`; if (/cube/.test(s)) { const a = nums(s)[0]; return a === undefined ? null : `${fmt(r2(6 * a * a))} (6 × ${fmt(a)}²)`; } if (/cylinder/.test(s) && r !== null && h !== null) return `${fmt(r2(2 * Math.PI * r * (r + h)))} (2πr(r + h))`; return null; } },
  { id: 'hypotenuse', family: 'physics', keywords: ['hypotenuse of', 'hypotenuse', 'pythagoras', 'missing side', 'other side'], arg: 'segment', keywordIsArg: true, example: ['hypotenuse 3 4', '5'], miss: 'need the two sides (or hypotenuse h side a)',
    run(arg) { const s = arg.toLowerCase(); const h = named(s, 'hypotenuse') ?? named(s, 'hyp'); const a = named(s, 'side') ?? named(s, 'leg'); if (h !== null && a !== null) return a >= h ? null : fmt(r2(Math.sqrt(h * h - a * a))); const xs = nums(s); if (xs.length < 2) return null; return fmt(r2(Math.hypot(xs[0], xs[1]))); } },
  { id: 'distance-between', family: 'physics', keywords: ['distance between', 'distance from'], arg: 'segment', example: ['distance between (1,2) and (4,6)', '5'], miss: 'need two points (x,y)',
    run(arg) { const pts = [...arg.matchAll(new RegExp(String.raw`\(\s*(${NUM})\s*,\s*(${NUM})\s*(?:,\s*(${NUM}))?\s*\)`, 'g'))]; if (pts.length < 2) return null; const [p, q] = pts; const d = Math.hypot(num(q[1]) - num(p[1]), num(q[2]) - num(p[2]), (q[3] ? num(q[3]) : 0) - (p[3] ? num(p[3]) : 0)); return fmt(r2(d)); } },
  { id: 'deg-rad', family: 'physics', keywords: ['in radians', 'to radians', 'in degrees', 'to degrees'], arg: 'segment', keywordIsArg: true, example: ['30 degrees in radians', '0.5236 (π/6)'], miss: 'need an angle',
    run(arg) { const s = arg.toLowerCase(); const v = nums(s.replace(/pi/g, ''))[0]; if (v === undefined) return null; const pi = /pi/.test(s); if (/(?:in|to) rad/.test(s)) { const r = v * Math.PI / 180; const frac = [1, 2, 3, 4, 6, 8, 12].find((k) => Math.abs(r * k / Math.PI - Math.round(r * k / Math.PI)) < 1e-9); const n = frac ? Math.round(r * frac / Math.PI) : 0; return `${fmt(Math.round(r * 10000) / 10000)}${frac ? ` (${n === 1 ? '' : n}π${frac === 1 ? '' : `/${frac}`})` : ''}`; } const rad = pi ? v * Math.PI : v; return `${fmt(r2(rad * 180 / Math.PI))}°`; } },
  { id: 'trig', family: 'physics', keywords: ['sin of', 'cos of', 'tan of', 'sine of', 'cosine of', 'tangent of', 'sin', 'cos', 'tan'], arg: 'segment', keywordIsArg: true, example: ['sin of 30 degrees', '0.5'], miss: 'need sin|cos|tan of <angle> (degrees unless you say rad)',
    run(arg) { const s = arg.toLowerCase(); const m = s.match(new RegExp(String.raw`(sin|cos|tan)[a-z]*\s*(?:of)?\s*\(?\s*(${NUM})\s*(rad|radians?|deg|degrees?|°)?`)); if (!m) return null; const v = num(m[2]); const rad = /^rad/.test(m[3] ?? '') ? v : v * Math.PI / 180; const f = m[1] === 'sin' ? Math.sin(rad) : m[1] === 'cos' ? Math.cos(rad) : Math.tan(rad); const out = Math.abs(f) > 1e12 ? 'undefined' : fmt(Math.round(f * 1e6) / 1e6); return out; } },
  { id: 'slope', family: 'physics', keywords: ['angle of slope', 'slope of', 'gradient of', 'slope'], arg: 'segment', example: ['slope 3 in 12', '14.04° (25% grade, 1 in 4)'], miss: 'need rise in run, or a %',
    run(arg) { const s = arg.toLowerCase(); let rise: number, run: number; const m = s.match(new RegExp(String.raw`(${NUM})\s*(?:in|:|over|/)\s*(${NUM})`)); if (m) { rise = num(m[1]); run = num(m[2]); } else { const p = s.match(new RegExp(String.raw`(${NUM})\s*%`)); if (!p) return null; rise = num(p[1]); run = 100; } if (!run) return null; const deg = Math.atan(rise / run) * 180 / Math.PI; return `${fmt(r2(deg))}° (${fmt(r2(rise / run * 100))}% grade, 1 in ${fmt(r2(run / rise))})`; } },
  { id: 'bmi', family: 'physics', keywords: ['bmi'], arg: 'segment', example: ['bmi 80kg 1.8m', '24.7 (normal, 18.5–24.9)'], miss: 'need weight (kg or lb) and height (m, cm, ft in)',
    run(arg) { const s = arg.toLowerCase(); const w = s.match(new RegExp(String.raw`(${NUM})\s*(${MASS})\b`)); const ft = s.match(new RegExp(String.raw`(\d)\s*(?:ft|'|feet|foot)\s*(\d{1,2})?\s*(?:in|")?`)); const hm = s.match(new RegExp(String.raw`(${NUM})\s*(m|meters?|metres?|cm)\b`)); if (!w) return null; const kg = toKg(num(w[1]), w[2]); const h = ft ? toM(Number(ft[1]) * 12 + Number(ft[2] ?? 0), 'in') : hm ? toM(num(hm[1]), hm[2]) : null; if (!h) return null; const bmi = kg / (h * h); const band = bmi < 18.5 ? 'underweight, < 18.5' : bmi < 25 ? 'normal, 18.5–24.9' : bmi < 30 ? 'overweight, 25–29.9' : 'obese, ≥ 30'; return `${fmt(Math.round(bmi * 10) / 10)} (${band})`; } },
  { id: 'bmr', family: 'physics', keywords: ['bmr', 'basal metabolic rate', 'calories to maintain'], arg: 'segment', example: ['bmr male 80kg 180cm 35', '1,755 kcal/day (Mifflin-St Jeor) · ×1.55 moderate 2,720'], miss: 'need male|female, weight, height, age',
    run(arg) { const s = arg.toLowerCase(); const w = s.match(new RegExp(String.raw`(${NUM})\s*(${MASS})\b`)); const hm = s.match(new RegExp(String.raw`(${NUM})\s*(m|meters?|metres?|cm)\b`)); const age = s.match(/(\d{1,3})\s*(?:years?|yrs?|y|yo|years old)?\s*(?:old)?$/) ?? s.match(/age\s*(\d{1,3})/); if (!w || !hm || !age) return null; const kg = toKg(num(w[1]), w[2]), cm = toM(num(hm[1]), hm[2]) * 100, a = Number(age[1]); const male = !/female|woman|f\b/.test(s); const bmr = 10 * kg + 6.25 * cm - 5 * a + (male ? 5 : -161); return `${withCommas(Math.round(bmr))} kcal/day (Mifflin-St Jeor) · ×1.55 moderate ${withCommas(Math.round(bmr * 1.55))}`; } },
  { id: 'heart-rate', family: 'physics', keywords: ['heart rate zones', 'heart rate zone', 'max heart rate', 'heart rate'], arg: 'segment', example: ['heart rate zones at 35', 'max 185 · z1 93–111 · z2 111–130 · z3 130–148 · z4 148–167 · z5 167–185'], miss: 'need an age',
    run(arg) { const a = nums(arg)[0]; if (a === undefined || a < 5 || a > 110) return null; const max = 220 - a; const z = (lo: number, hi: number) => `${Math.round(max * lo)}–${Math.round(max * hi)}`; return `max ${max} · z1 ${z(0.5, 0.6)} · z2 ${z(0.6, 0.7)} · z3 ${z(0.7, 0.8)} · z4 ${z(0.8, 0.9)} · z5 ${z(0.9, 1)}`; } },
  { id: 'pace', family: 'physics', keywords: ['pace', 'pace for'], arg: 'segment', example: ['pace 5k in 24:30', '4:54 /km (7:53 /mi) · 12.24 km/h'], miss: 'need a distance and a time (mm:ss)',
    run(arg) { const s = arg.toLowerCase(); const km = distKm(s.replace(/marathon/, '42.195 km').replace(/half\s*42.195 km/, '21.0975 km')); const secs = parseClockSecs(s); if (km === null || secs === null || km <= 0) return null; const perKm = secs / km, perMi = secs / (km / 1.609344); return `${clock(perKm)} /km (${clock(perMi)} /mi) · ${fmt(r2(km / (secs / 3600)))} km/h`; } },
  { id: 'speed', family: 'physics', keywords: ['speed', 'average speed'], arg: 'segment', example: ['speed 10km in 48 min', '12.5 km/h (7.77 mph, 4:48 /km)'], miss: 'need a distance and a time',
    run(arg) { const s = arg.toLowerCase(); const km = distKm(s); const t = s.match(new RegExp(String.raw`(${NUM})\s*(h|hours?|hrs?|min|minutes?|mins?|s|secs?|seconds?)\b`)); let secs = parseClockSecs(s); if (secs === null && t) secs = num(t[1]) * (/^h/.test(t[2]) ? 3600 : /^m/.test(t[2]) ? 60 : 1); if (km === null || secs === null || !secs) return null; const kmh = km / (secs / 3600); return `${fmt(r2(kmh))} km/h (${fmt(r2(kmh / 1.609344))} mph, ${clock(secs / km)} /km)`; } },
  { id: 'fuel', family: 'physics', keywords: ['fuel for', 'fuel', 'petrol for', 'litres for'], arg: 'segment', example: ['fuel 400 km at 6.5 l/100km', '26 L (400 km at 6.5 L/100 km)'], miss: 'need <distance> at <l/100km> or <mpg>',
    run(arg) { const s = arg.toLowerCase(); const km = distKm(s); const l100 = s.match(new RegExp(String.raw`(${NUM})\s*l\s*(?:/|per)\s*100`)); const mpg = s.match(new RegExp(String.raw`(${NUM})\s*mpg`)); if (km === null) return null; if (l100) { const l = km * num(l100[1]) / 100; return `${fmt(r2(l))} L (${fmt(r2(km))} km at ${l100[1]} L/100 km)`; } if (mpg) { const gal = (km / 1.609344) / num(mpg[1]); return `${fmt(r2(gal))} gal (${fmt(r2(gal * 3.785))} L) at ${mpg[1]} mpg`; } return null; } },
  { id: 'mpg', family: 'physics', keywords: ['mpg to l/100km', 'l/100km to mpg', 'mpg in l/100km', 'mpg'], arg: 'segment', keywordIsArg: true, example: ['35 mpg to l/100km', '6.72 L/100 km (US gallon); 8.07 UK'], miss: 'need <n> mpg or <n> l/100km',
    run(arg) { const s = arg.toLowerCase(); const v = nums(s.replace(/100/g, ''))[0]; if (v === undefined || v <= 0) return null; if (/l\s*\/\s*100\s*km\s+(?:to|in)\s+mpg|^\s*[\d.]+\s*l/.test(s) && !/mpg\s+(?:to|in)/.test(s)) return `${fmt(r2(235.215 / v))} mpg (US); ${fmt(r2(282.481 / v))} mpg (UK)`; return `${fmt(r2(235.215 / v))} L/100 km (US gallon); ${fmt(r2(282.481 / v))} UK`; } },
  { id: 'kinetic-energy', family: 'physics', keywords: ['kinetic energy of', 'kinetic energy'], arg: 'segment', example: ['kinetic energy 2kg at 3m/s', '9 J (½ × 2 × 3²)'], miss: 'need a mass and a speed',
    run(arg) { const s = arg.toLowerCase(); const m = s.match(new RegExp(String.raw`(${NUM})\s*(${MASS})\b`)); const v = s.match(new RegExp(String.raw`(${NUM})\s*(m/s|mps|km/h|kmh|mph)`)); if (!m || !v) return null; const kg = toKg(num(m[1]), m[2]); const ms = v[2] === 'km/h' || v[2] === 'kmh' ? num(v[1]) / 3.6 : v[2] === 'mph' ? num(v[1]) * 0.44704 : num(v[1]); const j = 0.5 * kg * ms * ms; return `${fmt(r2(j))} J (½ × ${fmt(kg)} × ${fmt(r2(ms))}²)`; } },
  { id: 'free-fall', family: 'physics', keywords: ['free fall', 'freefall', 'drop for', 'fall for'], arg: 'segment', example: ['free fall 5 seconds', '122.63 m, 49.05 m/s (no air resistance)'], miss: 'need seconds, or a height in m',
    run(arg) { const s = arg.toLowerCase(); const t = s.match(new RegExp(String.raw`(${NUM})\s*(?:s|secs?|seconds?)\b`)); if (t) { const tt = num(t[1]); return `${fmt(r2(0.5 * 9.81 * tt * tt))} m, ${fmt(r2(9.81 * tt))} m/s (no air resistance)`; } const h = s.match(new RegExp(String.raw`(${NUM})\s*(${LEN})\b`)); if (h) { const hh = toM(num(h[1]), h[2]); const tt = Math.sqrt(2 * hh / 9.81); return `${fmt(r2(tt))} s, lands at ${fmt(r2(9.81 * tt))} m/s (no air resistance)`; } return null; } },
  { id: 'ohms-law', family: 'physics', keywords: ["ohm's law", 'ohms law', 'ohm law'], arg: 'segment', example: ['ohms law 12v 4 ohm', '3 A · 36 W (V = I R)'], miss: 'need two of V, I (a), R (ohm)',
    run(arg) { const s = arg.toLowerCase(); const V = s.match(new RegExp(String.raw`(${NUM})\s*(?:v|volts?)\b`)), I = s.match(new RegExp(String.raw`(${NUM})\s*(?:a|amps?|amperes?)\b`)), R = s.match(new RegExp(String.raw`(${NUM})\s*(?:ohms?|Ω)`)); const v = V ? num(V[1]) : null, i = I ? num(I[1]) : null, r = R ? num(R[1]) : null; if (v !== null && r !== null && r) return `${fmt(r2(v / r))} A · ${fmt(r2(v * v / r))} W (V = I R)`; if (v !== null && i !== null && i) return `${fmt(r2(v / i))} Ω · ${fmt(r2(v * i))} W`; if (i !== null && r !== null) return `${fmt(r2(i * r))} V · ${fmt(r2(i * i * r))} W`; return null; } },
  { id: 'watts', family: 'physics', keywords: ['watts from', 'watts for', 'power from', 'watts'], arg: 'segment', example: ['watts from 230v 3a', '690 W (230 V × 3 A)'], miss: 'need volts and amps',
    run(arg) { const s = arg.toLowerCase(); const V = s.match(new RegExp(String.raw`(${NUM})\s*(?:v|volts?)\b`)), I = s.match(new RegExp(String.raw`(${NUM})\s*(?:a|amps?)\b`)); if (!V || !I) return null; return `${fmt(r2(num(V[1]) * num(I[1])))} W (${V[1]} V × ${I[1]} A)`; } },
  { id: 'kwh-cost', family: 'physics', keywords: ['kwh cost', 'electricity cost', 'cost to run', 'energy cost'], arg: 'segment', example: ['kwh cost 1500w for 3h at 0.28', '4.5 kWh = 1.26 (at 0.28/kWh)'], miss: 'need <watts> for <hours> at <price per kWh>',
    run(arg) { const s = arg.toLowerCase(); const w = s.match(new RegExp(String.raw`(${NUM})\s*(kw|w|watts?|kilowatts?)\b`)); const h = s.match(new RegExp(String.raw`(${NUM})\s*(?:h|hours?|hrs?)\b`)); const p = s.match(new RegExp(String.raw`(?:at|@)\s*(${NUM})`)); if (!w || !h) return null; const kw = /^k/.test(w[2]) ? num(w[1]) : num(w[1]) / 1000; const kwh = kw * num(h[1]); const daily = /(?:a|per) day/.test(s); return p ? `${fmt(r2(kwh))} kWh = ${fmt(r2(kwh * num(p[1])))} (at ${p[1]}/kWh)${daily ? ` · ${fmt(r2(kwh * num(p[1]) * 30))}/month` : ''}` : `${fmt(r2(kwh))} kWh`; } },
  { id: 'constant', family: 'physics', keywords: ['speed of light', 'speed of sound', 'gravitational constant', 'planck constant', 'avogadro constant', 'avogadro', 'boltzmann constant', 'electron charge', 'absolute zero', 'golden ratio', 'astronomical unit', 'light year', 'parsec', 'distance to the moon', 'distance to the sun', 'radius of the earth', 'circumference of the earth', 'value of pi', 'eulers number'], arg: 'segment', optionalArg: true, keywordIsArg: true, example: ['speed of light', '299,792,458 m/s (c; ≈ 3.0 × 10⁸ m/s, 1 079 252 849 km/h)'], miss: '',
    run(arg) { const s = arg.toLowerCase().replace(/\bvalue of\b|\bwhat is\b|\bthe\b/g, ' ').replace(/\s+/g, ' ').trim(); const k = Object.keys(CONSTANTS).find((c) => s.includes(c)) ?? (s === 'eulers number' || s === "euler's number" ? 'euler' : s === 'pi' ? 'pi' : null); return k ? CONSTANTS[k] : null; } },
  { id: 'gravity-on', family: 'physics', keywords: ['gravity on', 'escape velocity of', 'day length on', 'year on', 'weight on'], arg: 'segment', keywordIsArg: true, example: ['gravity on mars', '3.72 m/s² (0.38 g); escape velocity 5.03 km/s; day 24 h 37 min; year 687 days'], miss: 'need a planet (or the moon / sun)',
    run(arg) { const s = arg.toLowerCase(); const p = Object.keys(PLANETS).find((k) => new RegExp(`\\b${k}\\b`).test(s)); if (!p) return null; const e = PLANETS[p]; const w = s.match(new RegExp(String.raw`(${NUM})\s*(${MASS})`)); if (/weight/.test(s) && w) { const kg = toKg(num(w[1]), w[2]); return `${fmt(r2(kg * e.g / 9.81))} kg-equivalent on ${p} (${fmt(r2(kg * e.g))} N)`; } if (/escape/.test(s)) return `${e.esc} km/s`; if (/day length/.test(s)) return e.day; if (/^year/.test(s)) return e.year; return `${e.g} m/s² (${fmt(r2(e.g / 9.81))} g); escape velocity ${e.esc} km/s; day ${e.day}; year ${e.year}`; } },
  { id: 'half-life', family: 'physics', keywords: ['half-life', 'half life', 'remaining after'], arg: 'segment', example: ['half-life remaining 100g after 3 half-lives', '12.5 g (100 × ½³)'], miss: 'need <amount> after <n> half-lives, or half-life <t> after <time>',
    run(arg) { const s = arg.toLowerCase(); const n = s.match(new RegExp(String.raw`after\s+(${NUM})\s*half`)); const amt = s.match(new RegExp(String.raw`(${NUM})\s*(g|kg|mg|units?|%)?\s+after`)) ?? s.match(new RegExp(String.raw`remaining\s+(${NUM})\s*(g|kg|mg|units?|%)?`)); if (n && amt) { const k = num(n[1]); const a = num(amt[1]); return `${fmt(a * Math.pow(0.5, k))}${amt[2] ? ` ${amt[2]}` : ''} (${fmt(a)} × ½${k === 1 ? '' : String(k).replace(/\d/g, (d) => '⁰¹²³⁴⁵⁶⁷⁸⁹'[Number(d)])})`; } const hl = s.match(new RegExp(String.raw`half-?life\s*(?:of)?\s*(${NUM})\s*([a-z]+)`)); const after = s.match(new RegExp(String.raw`after\s+(${NUM})\s*([a-z]+)`)); if (hl && after && hl[2][0] === after[2][0]) { const frac = Math.pow(0.5, num(after[1]) / num(hl[1])); return `${pctf(frac)} remains (${fmt(r2(num(after[1]) / num(hl[1])))} half-lives)`; } return null; } },
  { id: 'decibels', family: 'physics', keywords: ['decibels', 'db plus', 'add decibels', 'db add'], arg: 'segment', keywordIsArg: true, example: ['decibels 90 plus 90', '93.01 dB (two equal sources add 3 dB)'], miss: 'need two levels in dB',
    run(arg) { const xs = nums(arg); if (xs.length < 2) return null; const total = 10 * Math.log10(xs.reduce((a, b) => a + Math.pow(10, b / 10), 0)); return `${fmt(r2(total))} dB${xs.length === 2 && xs[0] === xs[1] ? ' (two equal sources add 3 dB)' : ''}`; } },
  { id: 'wavelength', family: 'physics', keywords: ['wavelength of', 'wavelength'], arg: 'segment', example: ['wavelength of 440hz', '77.95 cm in air (sound); 681.35 km (radio)'], miss: 'need a frequency (hz, khz, mhz, ghz)',
    run(arg) { const m = arg.toLowerCase().match(new RegExp(String.raw`(${NUM})\s*(hz|khz|mhz|ghz)`)); if (!m) return null; const f = num(m[1]) * ({ hz: 1, khz: 1e3, mhz: 1e6, ghz: 1e9 } as Record<string, number>)[m[2]]; const sound = 343 / f, radio = 299792458 / f; const len = (x: number) => x >= 1000 ? `${fmt(r2(x / 1000))} km` : x >= 1 ? `${fmt(r2(x))} m` : x >= 0.01 ? `${fmt(r2(x * 100))} cm` : `${fmt(r2(x * 1000))} mm`; return `${len(sound)} in air (sound); ${len(radio)} (radio)`; } },
  { id: 'note-for', family: 'physics', keywords: ['note for', 'note at', 'frequency of', 'pitch of'], arg: 'segment', keywordIsArg: true, example: ['note for 440hz', 'A4 (440 Hz, A = 440)'], miss: 'need <n> hz, or a note like C5',
    run(arg) { const s = arg.toLowerCase(); const hz = s.match(new RegExp(String.raw`(${NUM})\s*hz`)); if (hz) { const f = num(hz[1]); const n = Math.round(12 * Math.log2(f / 440)) + 69; const cents = Math.round(1200 * Math.log2(f / (440 * Math.pow(2, (n - 69) / 12)))); return `${NOTES[n % 12]}${Math.floor(n / 12) - 1}${cents ? ` ${cents > 0 ? '+' : ''}${cents} cents` : ''} (${fmt(f)} Hz, A = 440)`; } const nm = s.match(/\b([a-g])(#|sharp|b|flat)?\s*(-?\d)\b/); if (!nm) return null; let idx = NOTES.indexOf(nm[1].toUpperCase()); if (nm[2] === '#' || nm[2] === 'sharp') idx++; if (nm[2] === 'b' || nm[2] === 'flat') idx--; const midi = (Number(nm[3]) + 1) * 12 + ((idx % 12) + 12) % 12; return `${fmt(r2(440 * Math.pow(2, (midi - 69) / 12)))} Hz (midi ${midi})`; } },
  { id: 'bpm', family: 'physics', keywords: ['bpm to ms', 'ms per beat', 'bpm'], arg: 'segment', example: ['bpm 120', '500 ms per beat · ¼ 125 ms · bar (4/4) 2 s'], miss: 'need a bpm',
    run(arg) { const b = nums(arg)[0]; if (!b) return null; const beat = 60000 / b; return `${fmt(r2(beat))} ms per beat · ¼ ${fmt(r2(beat / 4))} ms · bar (4/4) ${fmt(r2(beat * 4 / 1000))} s`; } },
  { id: 'aspect-ratio', family: 'physics', keywords: ['aspect ratio of', 'aspect ratio', 'ratio of'], arg: 'segment', example: ['aspect ratio 1920x1080', '16:9 (1.78)'], miss: 'need <w>x<h>',
    run(arg) { const m = arg.toLowerCase().match(/(\d+)\s*(?:x|×|by|:)\s*(\d+)/); if (!m) return null; const w = Number(m[1]), h = Number(m[2]); const gcd = (a: number, b: number): number => b ? gcd(b, a % b) : a; const g = gcd(w, h); return `${w / g}:${h / g} (${fmt(r2(w / h))})`; } },
  { id: 'scale', family: 'physics', keywords: ['scale', 'resize'], arg: 'segment', example: ['scale 1920x1080 to width 1280', '1280×720'], miss: 'need <w>x<h> to width|height <n>',
    run(arg) { const s = arg.toLowerCase(); const m = s.match(/(\d+)\s*(?:x|×|by)\s*(\d+)/); const t = s.match(/(?:to\s+)?(width|height|w|h)\s*(?:of)?\s*(\d+)/) ?? s.match(/to\s+(\d+)\s*(?:wide|px)?/); if (!m || !t) return null; const w = Number(m[1]), h = Number(m[2]); const byH = /^h/.test(t[1] ?? ''); const n = Number(t[2] ?? t[1]); return byH ? `${Math.round(w * n / h)}×${n}` : `${n}×${Math.round(h * n / w)}`; } },
  { id: 'dpi', family: 'physics', keywords: ['pixels for', 'dpi for', 'dpi'], arg: 'segment', keywordIsArg: true, example: ['dpi 300 at 6x4 inches', '1800×1200 px'], miss: 'need <dpi> and <w>x<h> inches (or cm)',
    run(arg) { const s = arg.toLowerCase(); const d = s.match(/(\d+)\s*(?:dpi|ppi)/) ?? s.match(/(?:dpi|ppi)\s*(\d+)/); const m = s.match(new RegExp(String.raw`(${NUM})\s*(?:x|×|by)\s*(${NUM})\s*(in|inch|inches|cm|")?`)); if (!d || !m) return null; const k = m[3] === 'cm' ? 1 / 2.54 : 1; return `${Math.round(num(m[1]) * k * Number(d[1]))}×${Math.round(num(m[2]) * k * Number(d[1]))} px`; } },
  { id: 'download-time', family: 'physics', keywords: ['download time', 'transfer time', 'time to download', 'how long to download'], arg: 'segment', example: ['download time 2gb at 50mbps', '5 min 20 s (2 GB at 50 Mbit/s)'], miss: 'need <size> at <speed>',
    run(arg) { const s = arg.toLowerCase(); const sz = s.match(new RegExp(String.raw`(${NUM})\s*(kb|mb|gb|tb)\b`)); const sp = s.match(new RegExp(String.raw`(${NUM})\s*(kbps|mbps|gbps|kb/s|mb/s|gb/s|kbit|mbit|gbit)`)); if (!sz || !sp) return null; const bytes = num(sz[1]) * ({ kb: 1e3, mb: 1e6, gb: 1e9, tb: 1e12 } as Record<string, number>)[sz[2]]; const isBytes = /b\/s$/.test(sp[2]); const bps = num(sp[1]) * ({ k: 1e3, m: 1e6, g: 1e9 } as Record<string, number>)[sp[2][0]] * (isBytes ? 8 : 1); const secs = bytes * 8 / bps; const h = Math.floor(secs / 3600), mi = Math.floor((secs % 3600) / 60), se = Math.round(secs % 60); return `${h ? `${h} h ` : ''}${mi ? `${mi} min ` : ''}${se} s (${sz[1]} ${sz[2].toUpperCase()} at ${sp[1]} ${isBytes ? sp[2].toUpperCase() : `${sp[2][0].toUpperCase()}bit/s`})`; } },
];
const pctf = (frac: number): string => `${fmt(r2(frac * 100))}%`;
