#!/usr/bin/env bash
# OpenCues × OpenAI Codex (Rust TUI) — install pipeline.
#
# Usage: ./setup.sh [codex-fork-dir]
#   default codex-fork-dir: $HOME/codex-cues
#
# What this does:
#   1. Clone openai/codex at pinned SHA into <fork> (idempotent — reuses if present)
#   2. Build @opencues/runtime so daemon.js exists
#   3. Copy patches/opencues-bridge/ into <fork>/codex-rs/opencues-bridge/
#   4. Add opencues-bridge to <fork>/codex-rs/Cargo.toml workspace members
#   5. Build the bridge crate with cargo (does NOT yet build full codex TUI —
#      that happens once the TUI patches land; see HANDOFF.md)
#   6. Drop a launch helper at <fork>/launch.sh
#
# Pinned upstream version: see PINNED_SHA below.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OPENCUES_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
FORK_DIR="${1:-$HOME/codex-cues}"

# Pinned to a known-good codex-rs SHA. Bump as upstream changes.
PINNED_SHA="d58d3cc"
PINNED_HUMAN="2026-04 (master at the time of writing)"

echo "=== OpenCues × OpenAI Codex setup ==="
echo "Target fork: $FORK_DIR"
echo "Pinned to codex SHA $PINNED_SHA ($PINNED_HUMAN)"

# 1. Clone or reuse the fork.
if [[ ! -d "$FORK_DIR" ]]; then
  echo "Cloning openai/codex..."
  git clone https://github.com/openai/codex.git "$FORK_DIR"
  cd "$FORK_DIR"
  git checkout "$PINNED_SHA" 2>/dev/null || echo "WARN: couldn't checkout $PINNED_SHA — using HEAD"
elif [[ ! -d "$FORK_DIR/codex-rs" ]]; then
  echo "Error: $FORK_DIR exists but doesn't look like a codex checkout."
  exit 1
else
  cd "$FORK_DIR"
fi

# 2. Build @opencues/runtime so daemon.js exists at the path the bridge expects.
echo ""
echo "Building @opencues/runtime..."
cd "$OPENCUES_ROOT"
pnpm --filter @opencues/runtime build

DAEMON_JS="$OPENCUES_ROOT/packages/opencues-runtime/dist/adapters/codex/v1/daemon.js"
if [[ ! -f "$DAEMON_JS" ]]; then
  echo "ERROR: daemon.js not built at $DAEMON_JS"
  echo "Check tsconfig — adapters/codex/v1/ must be in the include path."
  exit 1
fi
echo "Daemon: $DAEMON_JS"

# 3. Copy the bridge crate into the codex workspace.
BRIDGE_SRC="$SCRIPT_DIR/opencues-bridge"
BRIDGE_DEST="$FORK_DIR/codex-rs/opencues-bridge"
echo ""
echo "Copying bridge crate..."
mkdir -p "$BRIDGE_DEST"
rsync -a --delete "$BRIDGE_SRC/" "$BRIDGE_DEST/" 2>/dev/null || cp -r "$BRIDGE_SRC/." "$BRIDGE_DEST/"

# 4. Add opencues-bridge to the workspace members list.
CARGO_TOML="$FORK_DIR/codex-rs/Cargo.toml"
if ! grep -q '"opencues-bridge"' "$CARGO_TOML"; then
  echo "Adding opencues-bridge to $CARGO_TOML workspace members..."
  python3 - "$CARGO_TOML" <<'PY'
import sys, re
p = sys.argv[1]
src = open(p).read()
# Inject right after "members = [" so we don't disturb existing entries.
new = re.sub(r'(members\s*=\s*\[)', r'\1\n    "opencues-bridge",', src, count=1)
if new == src:
  print("WARN: couldn't find 'members = [' in Cargo.toml — please add manually")
else:
  open(p, 'w').write(new)
PY
else
  echo "opencues-bridge already in workspace members."
fi

# 5. Build the bridge crate (NOT the full codex TUI yet — see HANDOFF.md
#    for the TUI patches that need to land before the full build is useful).
echo ""
echo "Building opencues-bridge..."
cd "$FORK_DIR/codex-rs"
cargo build -p opencues-bridge --release 2>&1 | tail -15
echo ""
echo "Smoke test (spawns daemon, sends text-change, exits)..."
cargo run -q --release --bin opencues-bridge-smoke -- "$DAEMON_JS" 2>&1 | tail -15

# 6. Drop a launch helper at the fork root.
LAUNCH_HELPER="$FORK_DIR/launch.sh"
cat > "$LAUNCH_HELPER" <<EOF
#!/usr/bin/env bash
# Launch helper for opencues-patched codex.
# Generated by integrations/codex/patches/setup.sh.
exec env OPENCUES_DAEMON_PATH="$DAEMON_JS" cargo run --release --manifest-path "$FORK_DIR/codex-rs/Cargo.toml" -p codex-tui -- "\$@"
EOF
chmod +x "$LAUNCH_HELPER"

echo ""
echo "=== Setup complete (infrastructure layer) ==="
echo ""
echo "Bridge crate built + smoke-tested. Daemon path:"
echo "  $DAEMON_JS"
echo ""
echo "Launch helper installed at:"
echo "  $LAUNCH_HELPER"
echo ""
echo "Next steps (manual, see integrations/codex/HANDOFF.md):"
echo "  - Wire the bridge into codex-rs/tui/src/bottom_pane/chat_composer.rs"
echo "  - Apply via setup.sh's STEP 4 (TODO marker)"
echo ""
echo "To run codex (once TUI patches land):"
if command -v opencues &>/dev/null; then
  echo "  opencues run codex"
else
  echo "  pnpm exec opencues run codex"
fi

# TODO STEP 4: in-place TUI patches via Python sed (mirrors integrations/opencode/patches/setup.sh).
# Patch points:
#   <fork>/codex-rs/tui/src/bottom_pane/chat_composer.rs
#     - add `bridge: Option<opencues_bridge::Bridge>` field to ChatComposer
#     - in `new()`: try Bridge::start; warn on failure
#     - in key-handling path: call bridge.dispatch_key(...) BEFORE normal handling
#     - in text-mutation path: call bridge.notify_text_change(...) AFTER mutation
#     - in render path: query bridge.directives() and apply highlight ranges to TextArea
#   <fork>/codex-rs/tui/Cargo.toml
#     - add: opencues-bridge = { path = "../opencues-bridge" }
#
# These edits aren't auto-applied because they involve Rust ownership/lifetime
# decisions in fast-evolving upstream code. See HANDOFF.md for the path.
