// CountriesBlank — country facts from a BUNDLED static dataset (offline,
// instant, no network). Read-only.
//
// Trigger phrases like "population of france", "capital of japan",
// "currency of brazil" → resolve <fact> + <country>, look the country up
// in the bundled table, return the requested field.
//
// History: this blank originally fetched restcountries.com/v3.1 live, but
// that API was fully deprecated June 2026 (every path 301s to a
// deprecation notice → the blank returned "<country>: not found"). The
// data is now bundled (`countries-data.ts`, generated by
// `scripts/gen-countries-data.cjs` from mledoze/countries +
// samayo/country-json). Country facts are stable; re-run the generator to
// refresh. Bundling also makes the blank instant and offline — no fetch,
// no rate limit, no API-death risk.

import type { Blank } from './types';
import COUNTRIES, { type CountryFacts } from './countries-data';

// Keyword phrase fragment → which field to surface.
// Order matters for partial matches (longest-first wins).
const FACT_PATTERNS: Array<[RegExp, FactKey]> = [
  [/population of|population/i,   'population'],
  [/capital of|capital/i,         'capital'],
  [/currenc(y|ies) of|currency/i, 'currency'],
  [/region of|region|continent of/i, 'region'],
  [/language(s)? of|language/i,   'languages'],
  [/area of|area|size of/i,       'area'],
];

type FactKey = 'population' | 'capital' | 'currency' | 'region' | 'languages' | 'area';

const SKIP_WORDS: ReadonlySet<string> = new Set([
  'of', 'the', 'a', 'an', 'is', '_',
  'population', 'capital', 'currency', 'currencies',
  'region', 'continent', 'language', 'languages',
  'area', 'size',
]);

/** Normalise to the dataset's key shape (lowercase, alnum + single spaces). */
function normKey(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim();
}

export interface CountriesBlankOptions {
  /** Override the dataset (testing). Defaults to the bundled table. */
  readonly data?: Record<string, CountryFacts>;
}

export class CountriesBlank implements Blank {
  readonly name = 'countries';
  readonly readOnly = true;
  private readonly _data: Record<string, CountryFacts>;

  constructor(opts: CountriesBlankOptions = {}) {
    this._data = opts.data ?? COUNTRIES;
  }

  /** Shape-captured arg is answerable iff it's in the offline table.
   *  Stamped as `argValidator` by ConfigLoader → a miss ("istanbul")
   *  never claims the `_` and fluid-blank answers the trick question. */
  validArg(arg: string): boolean {
    // Same skip-word strip pickCountry applies, so "the netherlands"
    // validates exactly when get() would have found it.
    const words = arg.toLowerCase().split(/\s+/).filter(w => w && !SKIP_WORDS.has(w));
    return normKey(words.join(' ')) in this._data;
  }

  // Async to satisfy the Blank contract; the lookup itself is synchronous.
  async get(keyword?: string, context?: string[]): Promise<string> {
    const fact = pickFact(keyword);
    const country = pickCountry(keyword, context);
    if (!fact) return '';
    // Misses are FEEDBACK, not data — the `[err]` sentinel makes
    // BlankFill fill only the `_` and keep the typed command editable
    // (same convention as note/sentinel). The pre-`[err]` shape
    // ("istanbul: not found") was substituted as if it were the answer
    // — observed live in Spotlight 2026-07-21 on the trick question
    // "capital of istanbul" (a city, not a country).
    if (!country) return '[err] name a country';

    const entry = this._data[normKey(country)];
    if (!entry) return `[err] "${country}" is not a country I know`;

    return `${entry.name} ${fact}: ${formatFact(fact, entry)}`;
  }
}

function pickFact(keyword?: string): FactKey | null {
  if (!keyword) return null;
  for (const [re, key] of FACT_PATTERNS) {
    if (re.test(keyword)) return key;
  }
  return null;
}

function pickCountry(keyword?: string, context?: string[]): string {
  // Strip the fact phrase from the keyword + concat with context, then
  // remove skip-words. The remaining content words are the country name.
  const all = [keyword, ...(context ?? [])]
    .filter(Boolean)
    .flatMap(s => s!.toLowerCase().split(/\s+/))
    .filter(w => w && !SKIP_WORDS.has(w));
  // Country names can be multi-word ("united states", "south korea") —
  // join the remaining words; the dataset indexes those + common aliases.
  return all.join(' ').trim();
}

function formatFact(fact: FactKey, entry: CountryFacts): string {
  switch (fact) {
    case 'population': {
      const n = entry.population;
      if (n == null) return 'unknown';
      if (n >= 1e9) return `${(n / 1e9).toFixed(1)}B`;
      if (n >= 1e6) return `${(n / 1e6).toFixed(1)}M`;
      if (n >= 1e3) return `${(n / 1e3).toFixed(0)}K`;
      return String(n);
    }
    case 'capital': return entry.capital ?? 'unknown';
    case 'region':  return entry.region ?? 'unknown';
    case 'area': {
      const a = entry.area;
      if (a == null) return 'unknown';
      return `${a.toLocaleString('en-US')} km²`;
    }
    case 'currency': {
      const c = entry.currency;
      if (!c) return 'unknown';
      return c.name ? `${c.name} (${c.code})` : c.code;
    }
    case 'languages': {
      const ls = entry.languages;
      if (!ls || ls.length === 0) return 'unknown';
      return ls.slice(0, 3).join(', ');
    }
  }
}
